### ISSUE TITLE
Float16 Lib

### ISSUE THREAD

**Issue by johannes-777** [RobTillaart/float16#2]
Hi Rob,
I have Float16 Lib from you but couldn't find it in your repos.  I found 2 issues:

1.  f32tof16 should use 
>     f16_bin= (sgn ? 0x8000 : 0x0000) | exp | man;
>     instead of   f16_bin= sgn ? 0x8000 : 0x0000 | exp | man;

2. A test over the whole f16 numberspace revealed issues with certain numbers, where the error to f32 is 50%.  
    Examples:
- F32 is -32764.726562, F16 is -16384.000000 -> error is -50.00%! F16 encoding: 0xF400
- F32 is -31.996500, F16 is -16.000000 -> error is -49.99%! F16 encoding: 0xCC00
- F32 is -7.999200, F16 is -4.000000 -> error is -49.99%! F16 encoding: 0xC400
- F32 is -1.999800, F16 is -1.000000 -> error is -49.99%! F16 encoding: 0xBC00
- F32 is -0.499900, F16 is -0.250000 -> error is -49.99%! F16 encoding: 0xB400
- F32 is -0.499900, F16 is -0.250000 -> error is -49.99%! F16 encoding: 0xB400
- F32 is -0.499900, F16 is -0.250000 -> error is -49.99%! F16 encoding: 0xB400
- F32 is 7.999300, F16 is 4.000000 -> error is 50.00%! F16 encoding: 0x4400
- F32 is 31.992901, F16 is 16.000000 -> error is 49.99%! F16 encoding: 0x4C00
- F32 is 511.911591, F16 is 256.000000 -> error is 49.99%! F16 encoding: 0x5C00
- F32 is 8190.818359, F16 is 4096.000000 -> error is 49.99%! F16 encoding: 0x6C00
- F32 is 32763.277344, F16 is 16384.000000 -> error is 49.99%! F16 encoding: 0x7400

Do you have any ideas?  I am using ESP32

**Comment by RobTillaart** [comment]
@johannes-777 
Merged the first pull request to have a new starting point.  (did not make a release 0.1.4 yet)

- Can you check if this version still has the bug?
- Can you write a minimal sketch that shows the problem?  (can be used in the unit test)

**Comment by RobTillaart** [comment]
- started with some unit tests ...
- and a lot of other testing ...
- fixed negative numbers

merged into master

**Comment by RobTillaart** [comment]
@johannes-777 
> A test over the whole f16 numberspace revealed issues with certain numbers, where the error to f32 is 50%.
Examples:
F32 is -32764.726562, F16 is -16384.000000 -> error is -50.00%! F16 encoding: 0xF400
F32 is -31.996500, F16 is -16.000000 -> error is -49.99%! F16 encoding: 0xCC00
...

Can you please check if the last master branch still shows this issue?  (or share the sketch so I can verify)

**Comment by RobTillaart** [comment]
0.1.4 will be released asap, so it can be published and tested in a broader audience.

----
done
added to the Arduino library manager.
published on https://platformio.org/lib/show/13206/float16

**Comment by RobTillaart** [comment]
@johannes-777 
0.1.5 in PR 
+ added basic math + some helper functions.
+ optimized the compare operators 
+ more examples

**Comment by RobTillaart** [comment]
@johannes-777 

FYI, 
today I reworked the float16 library to fix a bug (issue #10) and correct the implementation of subnormal numbers (< 0.00006...)
Just to let you know.
The new version 0.2.0 will be released later this week.
